import DefaultLayout from "@/components/DefaultLayout";
import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { Navigation } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/navigation";
import { useEffect, useState } from "react";
import axios from "axios";
import ProductsGrid from "@/components/ProductsGrid";
import useWindowSize from "@/hooks/useWindowSize";
const { apiUrl } = require("@/helpers/config");



export default function Home(props) {
  const [home, setHome] = useState({});
  const { staticContent, cookies, setSplashLoading, categories, setPageLoading } = props;
  const {width} = useWindowSize();
  useEffect(() => {
    (async () => {
      const res = await axios.get(`${apiUrl}/home`);
      if (res.status === 200) {
        setHome(await res?.data?.item?.data);
        setPageLoading(false);
      }
    })();
  }, []);

  useEffect(() => {
    if (cookies && categories !== [] && home !== {}) {
      setSplashLoading(false);
    }
  }, [cookies, home, categories]);

  return (
    <DefaultLayout {...props}>
      <Head>
        <title>{staticContent?.home?.head?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.hero}>
          <img
            className={styles.heroLine}
            src="/img/heroLine.svg"
            alt="heroLine"
          />
          <div className={styles.start}>
            <img
              className={styles.bg}
              src="/img/heroEndBg.svg"
              alt="heroEndBg"
            />
            <img
              className={styles.heroStartImg}
              src="/img/heroStartImg.png"
              alt="heroStartImg"
            />
            <img className={styles.tag} src="/img/tag.png" alt="tag" />
          </div>
          <div className={styles.center}>
            <img
              className={styles.bg}
              src="/img/heroCenterBg.svg"
              alt="heroCenterBg"
            />
            <img
              className={styles.heroCenterImg}
              src="/img/heroCenterImg.png"
              alt="heroCenterImg"
            />
            <img className={styles.slogan} src="/img/slogan.png" alt="slogan" />
          </div>
          <div className={styles.end}>
            <img src="/img/heroEndBg.svg" alt="heroEndBg" />
            <img
              className={styles.heroEndImg}
              src="/img/heroEndImg.png"
              alt="heroEndImg"
            />
          </div>
        </div>
        <div className={styles.offers}>
          <Swiper
            initialSlide={1}
            spaceBetween={width > 820 ? -230 : 10}
            centeredSlides={true}
            navigation={true}
            modules={[Navigation]}
            className={styles.offersSwiper}
          >
            {home?.slider?.data?.map((offer, index) => {
              return (
                <SwiperSlide key={index}>
                  <div className={styles.offer}>
                    <img
                      src={offer?.image}
                      alt={`sliderImg0${index + 1}`}
                    />
                    <div className={styles.offerInfo}>
                      <div className={styles.title}>عرض خاص</div>
                      <p className={styles.desc}>لوريم ايبسوم دولار سيت أميت ,كونسيكتيتور أدايبا يسكينج أليايت,سيت دو أيوسمود تيمبور أنكايديديونتيوت لابوري ات دولار ماجنا</p>
                      <button>{staticContent?.home?.shopNow}</button>
                    </div>
                  </div>
                </SwiperSlide>
              );
            })}
          </Swiper>
        </div>
        <div className={styles.about}>
          <div className={styles.title}>{staticContent?.home?.aboutTitle}</div>
          <div className={styles.desc}>
            لوريم ايبسوم دولار سيت أميت ,كونسيكتيتور أدايبا يسكينج أليايت,سيت دو
            أيوسمود تيمبور أنكايديديونتيوت لابوري ات دولار ماجنا أليكيوا يوت
            انيم أد مينيم فينايم,كيواس نوستريد أكسير سيتاشن يللأمكو لابورأس نيسي
            يت أليكيوب أكس أيا كوممودو كونسيكيوات ديواس أيوتي أريري دولار إن
            ريبريهينديرأيت فوليوبتاتي فيلايت أيسسي كايلليوم دولار أيو فيجايت
            نيولا باراياتيور. أيكسسيبتيور ساينت أوككايكات كيوبايداتات
          </div>
          <div className={styles.videoContainer}>
            <video
              src="/img/aboutVideo.mp4"
              width="100%"
              type="video/mp4"
              autoPlay
              muted
              loop
            />
          </div>
        </div>
        <div className={styles.bestSellers}>
          <div className={styles.title}>
            {staticContent?.home?.bestSellersTitle}
          </div>
          <ProductsGrid data={home?.best_sellers?.data} />
        </div>
      </main>
    </DefaultLayout>
  );
}
